name: backup
description: "A new Flutter project."

# Publicación del paquete (opcional)
publish_to: 'none' # Eliminar esta línea si deseas publicar en pub.dev

# Versión y número de compilación
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  # Dependencias adicionales
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0
  pdf: ^3.11.1
  flutter_email_sender: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Fuentes personalizadas
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

